package com.ikonique.userService;

import java.util.List;

import com.ikonique.bean.Area;
import com.ikonique.bean.Booking;
import com.ikonique.bean.BookingInfo;
import com.ikonique.bean.Cart;
import com.ikonique.bean.Category;
import com.ikonique.bean.FeedBack;
import com.ikonique.bean.Offer;
import com.ikonique.bean.Order;
import com.ikonique.bean.OrderDetails;
import com.ikonique.bean.Product;
import com.ikonique.bean.SubCategory;
import com.ikonique.bean.User;
import com.ikonique.bean.Wishlist;
import com.ikonique.bean.roomdesign;

public interface userService {

	public String saveUserDetails(User user) ;
	public String saveDesignerDetails(User user);
	public List<Area> fatcharea();
	public User getUser(String email, String password);
	public String getAreaName(int id);
	public String updateUserDetails(User user);
	public String deleteUserDetails(int user_id);
	public User getEmailId(String email);
	public String updatePass(String cpass, int user_id);
	public List<User> fetchuserdetails();
	public List<User> fetchdesignerdetails();
	public List<Category> fetchcategorydetails();
	public List<SubCategory> fetchsubcategorydetails();
	public String insertProductDetails(Product product);
	public String insertCategoryDetails(Category category);
	public String insertSubCategoryDetails(SubCategory subcategory);
	public List<Product> fetchproductdetails();
	public List<SubCategory> fetchSubCategory(int categoryid);
	public List<Offer> SelectOfferDetails();
	public String insertOfferDetails(Offer offer);
	public String removecategoryDetails(int categoryId);
	public String removesubcategoryDetails(int subcategoryId);
	public String removeProductDetails(int productid);
	public String removeOfferDetails(int offerid);
	public Category fetchCategoryDetails(int categoryid);
	public String updateCategoryDetails(Category category);
	public SubCategory fetchSubCategoryDetails(int subcatid);
	public String updateSubCategoryDetails(SubCategory subcategory);
	public String updateProductDetails(Product product);
	public Offer fetchOfferDetails(int offerid);
	public String updateOfferDetails(Offer offer);
	public Product SelectProductDetail(int productid);
	public String modifyPass(String confirmpass, int user_id);
	public String insertIntoWishlist(Wishlist wishlist);
	public String deleteIntoWishlist(Wishlist wishlist);
	public List<Wishlist> fetchWishlistDetails(int i);
	public User getUserDetails(int user_id);
	public String insertFeedbackDetails(FeedBack feedBack);
	public List<FeedBack> fetchfeedbackdetails();
	public FeedBack getfeedbackland(int feedbackid);
	public String deleteFromFeedback(int feedbackid);
	public List<Product> selectProductDetail(int id) ;
	public User getDesigner(int designerid);
	public String deleteFromWishlist(int productcid, int user_id);
	public String insertIntoCart(Cart cart);
	public List<Cart> fetchCartDetails(int user_id);
	public String deleteFromCart(int productid, int user_id);
	public int insertBookingDetails(Booking booking);
	public String insertBookingInfo(BookingInfo bookingInfo);
	public String insertInCart(Cart cart);
	public String deleteInCart(Cart cart);
	public List<FeedBack> fatchProductFeedbacks(int productId);
	public List<Booking> selectBookingDetails() ;
	public List<BookingInfo> selectBookingInfoDetails();
	public List<roomdesign> fetchroomdesigndetails();
	public List<BookingInfo> selectPreviousBookingInfo() ;
	public int insertOrderDetails(Order order) ;
	public int updatePaymentStatus(int bookid);
	public String insertOrderInformation(OrderDetails orderDetails);
	public List<Order> selectOrderTableDetails();
	public List<OrderDetails> selectOrderDetails();
	public int updateOrderPaymentStatus(int bookid);
	public int deleteUserCart(int userid);
	public List<OrderDetails> getProductAndQuantity(int bookid);
	public int updateQuantityInProduct(int productid, int quantity);
	public List<Product> selectProductDetail(int subcatid, int minprice, int maxprice);
	public String removechildsubcategory(int categoryId);
}
